import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.scss";

export default function Home() {
  const [location, setLocation] = useState("");

  const handleInput = (e) => {
    e.preventDefault();
    console.log(e.target.value);
    setLocation(e.target.value);
  };

  const getWeather = (e) => {
    e.preventDefault();
    console.log(location);
    fetch(`/api/weather?address=${location}`)
      .then((res) => res.json())
      .then((data) => console.log(data));
  };

  const handleSubmit = (e) => {};
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/weather.png" />
      </Head>
      <main>
        <h1>Weather App</h1>

        <form onSubmit={handleSubmit}>
          <input
            type="text"
            value={location}
            onChange={handleInput}
            placeholder="Location"
          />
          <button type={"submit"} onClick={getWeather}>
            Search
          </button>
        </form>
      </main>
    </>
  );
}
